### ISSUE TITLE
Feature Request: Enable/Disable signal

### ISSUE THREAD

**Issue by minitoine** [Lusito/typed-signals#7]
Hi,

Would it possible possible to add the possibility to [temporarily] disable a signal while maintaining the active connections? 
Until now, you can collect signals connections in a collection and disable/enable them, but you can't do it to the source.
For example:

```
let mySignal = new Signal<() => void>();
function handler42() {}
function handler666() {}
mySignal.connect(handler42);
mySignal.connect(handler46);

mySignal.enabled = false;
mySignal.emit(); // won't call both handlers
mySignal.enabled = true;
```

Why ?
Cause you don't obviously have access to the connections of a signal and can't disable all of them.

Concrete exemple:
```
let mySignal = new Signal();

##### Somewhere in your code #####
function process(arg) {
     // some processing
     mySignal.emit();
}


##### Elsewhere in your code #####
function update() {
    // some heavy update
}
mysignal.connect(update);

##### one call one update #####
process(obj) 

##### multiple calls  one update #####
mySignal.disable = false;
for (let obj of array) {
     process(obj)
}
mySignal.enable = true;
mySignal.emit();
```

Best,

minitoine

**Comment by Lusito** [comment]
Hi, and thanks for the idea. The example seems like a very unusual use-case, maybe even an anti-pattern and I am unsure if this should be part of the library.

I mainly see this as a problem, because there are situations (collectors), where the listeners are supposed to return values and it's unclear what the desired behavior would be in this case.

Here are a few ideas how you can solve the problem yourself:

## 1. Do not emit during process:

If you shift the responsibility to emit the signal from process to the caller of process, you avoid the problem:

```typescript
let mySignal = new Signal();

// ##### Somewhere in your code #####
function process(arg) {
     // some processing
}


// ##### Elsewhere in your code #####
function update() {
    // some heavy update
}
mysignal.connect(update);

// ##### one call one update #####
process(obj) 
mySignal.emit();

// ##### multiple calls  one update #####
for (let obj of array) {
     process(obj)
}
mySignal.emit();
```


## 2. Don't do heavy work within signal listeners

This is a good idea for other situations too: Don't do heavy work within a listener. You could for example set a dirty flag and handle it the next time you actually need the changes to be applied. For example if you need to sort a list of items whenever a signal happened, just set a flag `needsResort=true` and the next time the list gets accessed and needsResort is true, set it to false and sort the items.

That way, your listener will call `needsResort=true` `array.length` times, but the actual sorting (heavy work) happens only once.

## 3. Use debounce or throttle

If you use a debounce or throttle function, you can limit the amount of emit calls by saying:
- debounce: will execute the last emit after x milliseconds. If the debounced function was called again within x milliseconds, the first call will be cancelled and the next one will have to wait x ms again. I.e. you call debouncedFn() 10 times within 5 ms, while the debouncetime is 10 ms, only one call (the last) goes through.
- throttle: A throttled function will be called immediately, but if another call happens within x milliseconds, it will be delayed to run after that time. If more calls happen during the x milliseconds, only one call will happen at the end. I.e. you call throttledFn() 10 times within 5ms while throttletime 10 ms, the first call goes through and the last one as well after 10 ms.

## 4. Extend Signal

If you really feel like you need the enabled flag on the signal and you don't think the above solutions fit your problem well, then you can easily do this yourself:

```typescript
class SignalEx<THandler extends (...args: any[]) => any> extends Signal<THandler> {
    public enabled = true;

    public emit(...args: Parameters<THandler>) {
        if (this.enabled) super.emit(...args);
    }

    protected emitCollecting(collector: Collector<THandler>, args: Parameters<THandler>) {
        if (this.enabled) super.emitCollecting(collector, args);
    }
}
```

## 5. Convince me otherwise

Feel free to convince me with a better scenario or maybe a more detailed scenario why it would be a good idea to add this to the library.

**Comment by minitoine** [comment]
Hi.

First of all, Wouah, such an elaborated answer. 

I resolved my "issue" by rewriting a lot of signals and functions and taking into account arrays. So instead of sending multiple signals for multiple objects, only one signal is emitted with an array arg. My use case, just for curiosity, is a notification system with a three.js scene when 3d objects are updated, etc etc.

Of course, I still can extend the signal class, but as you recommended (and I agree), I will try to avoid this as this is kind of anti pattern.

I fair new to js (and ts) and I didn't know throttle or debounce, very interesting indeed, especially in my context of a 3d app. Definetly going to use it a lot of time in my code.

The idea came from the three.js editor source code, where they disable a signal, do some modifications that emit the signal, and then re-enable it ([SetSceneCommand example](https://github.com/mrdoob/three.js/blob/master/editor/js/commands/SetSceneCommand.js)). This is probably a bad example and I guess there is always a way to avoid this behavior.

Thank you for your time.
